version: "3"

services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6380:6379"  # Map host port 6380 to container port 6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  app:
    build: .
    container_name: medagent
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    ports:
      - "8001:8001"
    command: >
        bash -c "uvicorn main:app --host=0.0.0.0 --port 8001"
    volumes:
      - .:/app

  
  agent_worker_1:
    build: .
    container_name: agent_worker_1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    command: celery --app workers.operations.app worker --loglevel=info
    volumes:
      - .:/app

  agent_worker_2:
    build: .
    container_name: agent_worker_2
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    command: celery --app workers.operations.app worker --loglevel=info
    volumes:
      - .:/app

volumes:
  redis_data:
